### ISSUE TITLE
Format-dependent pronunciation rules

### ISSUE THREAD

**Issue by rom1mouret** [daisy/pipeline-mod-tts#41]
Some TTS processors do not properly pronounce roman numerals in titles. It is possible to transform the content to make sure they will be pronounced properly, but we can't do it in text-to-ssml module because at this point we no longer know what a title looks like. It has to be customized for each format (i.e. Zedai, DTBook and HTML) before calling text-to-ssml.

I see two options:
- Extend the existing annotation mechanism. It is currently designed to insert SSML before and after elements, not to modify the input.
- Run a dedicated stylesheet in dtbook-to-ssml, zedai-to-ssml and epub3-to-ssml. Whether it must be configurable is open to debate.

**Comment by bertfrees** [comment]
Looks like this has been fixed by https://github.com/daisy/pipeline-mod-tts/pull/47.
