### ISSUE TITLE
Externalize the list of well-known voices

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-mod-tts#5]
Currently the list of known voices is hard-coded in an array in ~~`TTSRegistry`~~ `VoiceManager`. It should be externalized in a config file, ideally outside the module to be manually editable by the end-user.

**Comment by bertfrees** [comment]
I think most straightforward would be to define the built-in voices in the static config file specified with the `org.daisy.pipeline.tts.config` property. In `VoiceManager` the voices from the (static and dynamic) config files are simply added together with the voices defined in Java.

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-mod-tts/pull/89
