### ISSUE TITLE
Make css-speech-inliner compatible with jStyleParser 1.20-p1

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-tts#65]
Use NetworkProcessor interface as in https://github.com/daisy/pipeline-mod-braille/commit/e189b6c9fce1eec3fd284243bf81abdc86db9991

**Comment by bertfrees** [comment]
- [ ] To do: move jStyleParser to a BOM that is imported by both mod-tts and mod-braille.

**Comment by rdeltour** [comment]
@bertfrees do you remember what's the status of this one? does it belong to `v1.10`?

**Comment by bertfrees** [comment]
This should be in 1.10 already: see https://github.com/daisy/pipeline-mod-tts/commit/01541ded87fcc6c550a98c20b933f53ca3f2d5e4.

**Comment by bertfrees** [comment]
And the version declaration was later moved to the framework BoM.

**Comment by rdeltour** [comment]
> This should be in 1.10 already

right, be can it be closed then?
