### ISSUE TITLE
[QUESTION] Acapela TTS-Server Linux 64bit

### ISSUE THREAD

**Issue by larsvoigt** [daisy/pipeline-mod-tts#67]
Hi, 
we have running the DP2 on ubuntu 16.04. Espeak as TTS-engine works very well. Now I have installed Acapela TTS-Server on this system.  And I will use Acapela as TTS-engine but it doesn't work. If I have a look within the DP2 job log, I can see the Acapela- engine will be not detected.  Do I need anything configure? 
Acapela is installed here ```/opt/Acapela/TTS-Server```
```
ls /opt/Acapela/TTS-Server/lib/
libiconv64.so.2 
libiconv64.so.2.1.0
libnscube64.so
```

Thanks for helping me.
Lars

**Comment by larsvoigt** [comment]
I found this [note](https://github.com/daisy/pipeline-mod-tts/blob/master/tts-utils/tts-adapter-acapela/src/main/java/org/daisy/pipeline/tts/acapela/AcapelaEngine.java#L34) but which path is mean :-)?

**Comment by josteinaj** [comment]
I haven't used the Acalepa voice so I'm not sure, but there's this document describing how the TTS configuration file (which you upload together with the input book in the webui or reference from the command line when starting a job): https://gist.github.com/rom1mouret/182e5da19dcccef84397

Maybe try running `echo $LD_LIBRARY_PATH` and see if you get any paths. My guess is that one of those paths needs to contain `libnscube.so`. I'm really not sure though, that's just my guess...

**Comment by alexbernier** [comment]
On Tue, Sep 06, 2016 at 06:26:05AM -0700, Lars Voigt wrote:
>    Hi,
>    we have running the DP2 on ubuntu 16.04. Espeak as TTS-engine works
>    very well. Now I have installed Acapela TTS-Server on this system. And
>    I will use Acapela as TTS-engine but it doesn't work. If I have look
>    within the DP2 job log, I can see the Acapela- engine will be not
>    detected. Do I need anything configure?
>    Acapela is installed here /opt/Acapela/TTS-Server
> ls /opt/Acapela/TTS-Server/lib/
> libiconv64.so.2
> libiconv64.so.2.1.0
> libnscube64.so

Hi,

On Debian here, I have a symbolic link : /usr/lib/libnscube64.so -> /opt/Acapela/TTS-Server/lib/libnscube64.so

You can also try :
# echo /opt/Acapela/TTS-Server/lib > /etc/ld.so.conf.d/acapela.conf
# ldconfig

Alex

Association BrailleNet

**Comment by larsvoigt** [comment]
Thank you guys @josteinaj @alexbernier for the hints!  The symbolic link was the solution :-). Anyway, now  I see it fixed only my first problem. The new problem is:  ```[ERROR] acapela-jna cannot be tested because no voice seems available.```. But I think that problem is independent form the DP. So I can close this issue. 

P.S.: Acapela TTS Engine test sample say ```Enumerating the voices .... ERROR : nscFindFirstVoice return 1.```
