### ISSUE TITLE
I just have one question,  how do I add a user in SSML?

### ISSUE THREAD

**Issue by 25kcdiez** [daisy/pipeline-mod-tts#79]
I just found this  Github  in google, 

  anyway  for example:
      ` "<speak> got it</speak>"  + NewPlayersName+ "<speak> right ? ....</speak>"`
    it returns  error in service response
   "<speak> got it</speak>kevin<speak> right ? ....</speak>";
 It return  SSML with Plain text "kevin" how do we exactly add a players  name or username with SSML?
or is it even possible in the current ALEXA  Version?

**Comment by bertfrees** [comment]
I have no idea. Is your issue even related to DAISY Pipeline?
